
POST  http://localhost:3001/api/persons
content-type: application/json 

{
    "name": "mj",
    "number": "333"
}

####

DELETE http://localhost:3001/api/persons/

###

PUT http://localhost:3001/api/persons/640a4c62a82f5691c565ab75
content-type: application/json 

{
    "name": "MJ",
    "number": "999"
}